export type WidgetType =
  | "star-rating"
  | "review-list"
  | "review-carousel"
  | "review-grid"
  | "masonry-grid"
  | "floating-badge";

export interface WidgetSettings {
  widgetName: string;
  enabled: boolean;
  placement: string;
  animation: string;
  primaryColor: string;
  accentColor: string;
  backgroundColor: string;
  textColor: string;
  borderColor: string;
  starColor: string;
  buttonColor: string;
  headingFontSize: number;
  bodyFontSize: number;
  fontWeight: string;
  letterSpacing: number;
  lineHeight: number;
  borderRadius: number;
  borderWidth: number;
  shadow: string;
  padding: number;
  gap: number;
  alignment: string;
  showAvatar: boolean;
  avatarShape: string;
  showVerifiedBadge: boolean;
  showReviewerName: boolean;
  showDate: boolean;
  showCountry: boolean;
  starSize: number;
  starFilled: boolean;
  starOutline: boolean;
  showLoadMoreButton: boolean;
  showWriteReviewButton: boolean;
  buttonRadius: number;
  buttonStyle: string;
  containerWidth: number;
  cardWidth: number;
  margins: number;
  verticalSpacing: number;
  customCss: string;
  enableAnimations: boolean;
  darkMode: boolean;
}

const defaultSettingsByType: Record<WidgetType, WidgetSettings> = {
  "star-rating": {
    widgetName: "Star Rating",
    enabled: true,
    placement: "product-header",
    animation: "fade",
    primaryColor: "#111111",
    accentColor: "#4B7A6A",
    backgroundColor: "#FFFFFF",
    textColor: "#111111",
    borderColor: "#E7E4DA",
    starColor: "#111111",
    buttonColor: "#111111",
    headingFontSize: 18,
    bodyFontSize: 14,
    fontWeight: "600",
    letterSpacing: 0,
    lineHeight: 1.5,
    borderRadius: 18,
    borderWidth: 1,
    shadow: "soft",
    padding: 20,
    gap: 16,
    alignment: "left",
    showAvatar: false,
    avatarShape: "circle",
    showVerifiedBadge: true,
    showReviewerName: true,
    showDate: true,
    showCountry: false,
    starSize: 18,
    starFilled: true,
    starOutline: false,
    showLoadMoreButton: false,
    showWriteReviewButton: false,
    buttonRadius: 999,
    buttonStyle: "solid",
    containerWidth: 680,
    cardWidth: 320,
    margins: 24,
    verticalSpacing: 16,
    customCss: "",
    enableAnimations: true,
    darkMode: false,
  },
  "review-list": {
    widgetName: "Review List",
    enabled: true,
    placement: "product-body",
    animation: "fade",
    primaryColor: "#111111",
    accentColor: "#4B7A6A",
    backgroundColor: "#FFFFFF",
    textColor: "#111111",
    borderColor: "#E7E4DA",
    starColor: "#111111",
    buttonColor: "#111111",
    headingFontSize: 20,
    bodyFontSize: 14,
    fontWeight: "500",
    letterSpacing: 0,
    lineHeight: 1.6,
    borderRadius: 20,
    borderWidth: 1,
    shadow: "soft",
    padding: 24,
    gap: 18,
    alignment: "left",
    showAvatar: true,
    avatarShape: "circle",
    showVerifiedBadge: true,
    showReviewerName: true,
    showDate: true,
    showCountry: true,
    starSize: 16,
    starFilled: true,
    starOutline: false,
    showLoadMoreButton: true,
    showWriteReviewButton: true,
    buttonRadius: 999,
    buttonStyle: "solid",
    containerWidth: 920,
    cardWidth: 320,
    margins: 24,
    verticalSpacing: 20,
    customCss: "",
    enableAnimations: true,
    darkMode: false,
  },
  "review-carousel": {
    widgetName: "Review Carousel",
    enabled: true,
    placement: "homepage-featured",
    animation: "slide",
    primaryColor: "#111111",
    accentColor: "#4B7A6A",
    backgroundColor: "#FFFFFF",
    textColor: "#111111",
    borderColor: "#E7E4DA",
    starColor: "#111111",
    buttonColor: "#111111",
    headingFontSize: 22,
    bodyFontSize: 14,
    fontWeight: "500",
    letterSpacing: 0,
    lineHeight: 1.6,
    borderRadius: 24,
    borderWidth: 1,
    shadow: "medium",
    padding: 24,
    gap: 20,
    alignment: "center",
    showAvatar: true,
    avatarShape: "circle",
    showVerifiedBadge: true,
    showReviewerName: true,
    showDate: true,
    showCountry: true,
    starSize: 16,
    starFilled: true,
    starOutline: false,
    showLoadMoreButton: false,
    showWriteReviewButton: true,
    buttonRadius: 999,
    buttonStyle: "outline",
    containerWidth: 980,
    cardWidth: 300,
    margins: 32,
    verticalSpacing: 20,
    customCss: "",
    enableAnimations: true,
    darkMode: false,
  },
  "review-grid": {
    widgetName: "Review Grid",
    enabled: true,
    placement: "homepage-grid",
    animation: "fade",
    primaryColor: "#111111",
    accentColor: "#4B7A6A",
    backgroundColor: "#FFFFFF",
    textColor: "#111111",
    borderColor: "#E7E4DA",
    starColor: "#111111",
    buttonColor: "#111111",
    headingFontSize: 20,
    bodyFontSize: 14,
    fontWeight: "500",
    letterSpacing: 0,
    lineHeight: 1.6,
    borderRadius: 22,
    borderWidth: 1,
    shadow: "soft",
    padding: 20,
    gap: 20,
    alignment: "left",
    showAvatar: true,
    avatarShape: "rounded",
    showVerifiedBadge: true,
    showReviewerName: true,
    showDate: true,
    showCountry: false,
    starSize: 16,
    starFilled: true,
    starOutline: false,
    showLoadMoreButton: true,
    showWriteReviewButton: false,
    buttonRadius: 14,
    buttonStyle: "ghost",
    containerWidth: 1040,
    cardWidth: 280,
    margins: 28,
    verticalSpacing: 18,
    customCss: "",
    enableAnimations: true,
    darkMode: false,
  },
  "masonry-grid": {
    widgetName: "Masonry Grid",
    enabled: true,
    placement: "collection-highlight",
    animation: "stagger",
    primaryColor: "#111111",
    accentColor: "#4B7A6A",
    backgroundColor: "#FFFFFF",
    textColor: "#111111",
    borderColor: "#E7E4DA",
    starColor: "#111111",
    buttonColor: "#111111",
    headingFontSize: 20,
    bodyFontSize: 14,
    fontWeight: "500",
    letterSpacing: 0,
    lineHeight: 1.65,
    borderRadius: 24,
    borderWidth: 1,
    shadow: "soft",
    padding: 20,
    gap: 16,
    alignment: "left",
    showAvatar: true,
    avatarShape: "circle",
    showVerifiedBadge: true,
    showReviewerName: true,
    showDate: true,
    showCountry: true,
    starSize: 16,
    starFilled: true,
    starOutline: false,
    showLoadMoreButton: true,
    showWriteReviewButton: false,
    buttonRadius: 14,
    buttonStyle: "solid",
    containerWidth: 1080,
    cardWidth: 260,
    margins: 28,
    verticalSpacing: 16,
    customCss: "",
    enableAnimations: true,
    darkMode: false,
  },
  "floating-badge": {
    widgetName: "Floating Badge",
    enabled: true,
    placement: "floating-corner",
    animation: "lift",
    primaryColor: "#111111",
    accentColor: "#4B7A6A",
    backgroundColor: "#FFFFFF",
    textColor: "#111111",
    borderColor: "#E7E4DA",
    starColor: "#111111",
    buttonColor: "#111111",
    headingFontSize: 18,
    bodyFontSize: 13,
    fontWeight: "600",
    letterSpacing: 0,
    lineHeight: 1.4,
    borderRadius: 999,
    borderWidth: 1,
    shadow: "medium",
    padding: 18,
    gap: 12,
    alignment: "center",
    showAvatar: false,
    avatarShape: "circle",
    showVerifiedBadge: false,
    showReviewerName: false,
    showDate: false,
    showCountry: false,
    starSize: 14,
    starFilled: true,
    starOutline: false,
    showLoadMoreButton: false,
    showWriteReviewButton: true,
    buttonRadius: 999,
    buttonStyle: "solid",
    containerWidth: 320,
    cardWidth: 260,
    margins: 24,
    verticalSpacing: 12,
    customCss: "",
    enableAnimations: true,
    darkMode: false,
  },
};

export const cloneWidgetSettings = (settings: WidgetSettings): WidgetSettings => JSON.parse(JSON.stringify(settings)) as WidgetSettings;

export const getDefaultWidgetSettings = (type: WidgetType): WidgetSettings => cloneWidgetSettings(defaultSettingsByType[type]);

export const normalizeWidgetType = (type: string | null | undefined): WidgetType => {
  const candidate = type as WidgetType | undefined;
  if (candidate && candidate in defaultSettingsByType) {
    return candidate;
  }
  return "review-list";
};